### PR TITLE
Add an index in Challenge collection for user and entries.user_id

### LINKED ISSUE #253: Slow database operation: add index?
Helpful suggestion from mLab...

image

/cc @Hettomei

### PR DESCRIPTION
**Pull request by Hettomei**
It was a suggestion from mLab
Fix #253 

After deploy, we need to run : 
```
rake db:mongoid:create_indexes
```

Code taken from official doc : https://docs.mongodb.com/mongoid/current/tutorials/mongoid-indexes/

Heres my log after rake task on local development - everythings seems ok - : 

```
D, [2018-09-16T21:34:02.726706 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.createIndexes | STARTED | {"createIndexes"=>"challenges", "indexes"=>[{"key"=>{"user_id"=>1}, "background"=>true, "name"=>"user_id_1"}], "lsid"=>{"id"=><BSON::Binary:0x46942577097600 type=uuid data=0xe8918a1b4213422f...>}}
D, [2018-09-16T21:34:02.728703 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.saslStart | STARTED | {}
D, [2018-09-16T21:34:02.729422 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.saslStart | SUCCEEDED | 0.000490849s
D, [2018-09-16T21:34:02.738417 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.saslContinue | STARTED | {}
D, [2018-09-16T21:34:02.739217 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.saslContinue | SUCCEEDED | 0.000497292s
D, [2018-09-16T21:34:02.739553 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.saslContinue | STARTED | {}
D, [2018-09-16T21:34:02.740251 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.saslContinue | SUCCEEDED | 0.0005139270000000001s
D, [2018-09-16T21:34:02.771913 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.createIndexes | SUCCEEDED | 0.044935433s
D, [2018-09-16T21:34:02.772498 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.createIndexes | STARTED | {"createIndexes"=>"challenges", "indexes"=>[{"key"=>{"entries.user_id"=>1}, "name"=>"entries.user_id_1"}], "lsid"=>{"id"=><BSON::Binary:0x46942577097600 type=uuid data=0xe8918a1b4213422f...>}}
D, [2018-09-16T21:34:02.783033 #3592] DEBUG -- : MONGODB | localhost:27017 | vimgolf_development.createIndexes | SUCCEEDED | 0.010440227s
I, [2018-09-16T21:34:02.783196 #3592]  INFO -- : MONGOID: Created indexes on Challenge:
I, [2018-09-16T21:34:02.783258 #3592]  INFO -- : MONGOID: Index: {:user_id=>1}, Options: {:background=>true}
I, [2018-09-16T21:34:02.783285 #3592]  INFO -- : MONGOID: Index: {:"entries.user_id"=>1}, Options: {}
D, [2018-09-16T21:34:02.793401 #3592] DEBUG -- : MONGODB | localhost:27017 | admin.endSessions | STARTED | {"endSessions"=>[{"id"=><BSON::Binary:0x46942577097600 type=uuid data=0xe8918a1b4213422f...>}]}
D, [2018-09-16T21:34:02.798718 #3592] DEBUG -- : MONGODB | localhost:27017 | admin.endSessions | SUCCEEDED | 0.005001246s
```

### CODE REVIEW

**Comment by Hettomei** [comment]
Side note : 
I don't know how index in mongodb works : 
I don't know if it really optimize or not, I don't know, if, like sql database we should add index for any *_id fields. If a mongodb expert can provide some feedback, I can then add the code in ruby

Any way, if performance are worst we can undo this operation by running : 

```
rake db:mongoid:remove_indexes
```

**Comment by Hettomei** [comment]
Every failing tests are tests about twitter widgets and is not related to this commit.

I raise an issue

**Comment by igrigorik** [comment]
Looks great, let's land this!

- Can you roll this out, do you need me to do it?
- Could we land the twitter fix as part of this PR? It would be nice to keep the tests green.

**Comment by Hettomei** [comment]
I can do the deploy + after deploy but I need your merge first.

Yes we can add twitter in this commit. I don't like to put different problem in same commit but if you prefere.

Also I don't know when I will have time to do the twitter part, maybe next week

**Comment by igrigorik** [comment]
sg, let's get this live.

**Pull request merged**
