### PR TITLE
Add 'How to contribute' in README.md and create seeds

### PR DESCRIPTION
**Pull request by Hettomei**
Hi

The goal of this PR is to ensure anybody can run a local instance.

When reading the issue, it looks like many people ask the same things 'too many error on heroku' 'please paginate...'
Maybe they did not propose PR because they are not able to run it locally.

I forget how to write ruby code/convention/best practice. So feel free to amend the PR/ or critics if I did not respect the standard.

I added some mongoDB logs to see the query. I can remove it

I force 'vimgolf/vimgolf' for database. I see you have done a PR that do "ENV['DATABASE_USERNAME']" why you do not merge ?

Thanks for this game.

### CODE REVIEW

**Comment by igrigorik** [comment]
@Hettomei it looks like the build is failing, can you please take a look at the output of https://travis-ci.org/igrigorik/vimgolf/jobs/361386252?

**Comment by Hettomei** [comment]
Off course I can take a look. I try to do it during this week.

**Comment by Hettomei** [comment]
I have not forgotten. Do not close this pr.

**Comment by Hettomei** [comment]
So : 
I think most of my problems comes from mongodb 3.6.3 : 
- cannot boot website if no 'challenges' collection
- database cleaner does not work

Bypassed these blockers by
- adding a rake db:seed (to create empty colletion)
- remove database cleaner, and do the job by myself.

I hope Travis will pass.

**Comment by Hettomei** [comment]
Travis is ok \o/

I see Travis is mongodb 2.6 and I am at 3.6. 

I m pretty sure you didn't planned to upgrade mongodb.... and my PR is not the best code you'll see today :)

Feel free to abandon this PR if it doesn't match your expectation.

**Comment by igrigorik** [comment]
Looks good! One nitpick on duplicate create method.. :)

**Comment by Hettomei** [comment]
Yes.

But I don't remember rails best practice : 
Is it ok if I just create an app/helpers/seed_helper.rb ?

**Comment by Hettomei** [comment]
New PR pushed.

**Comment by igrigorik** [comment]
Awesome work, thank you!

**Pull request merged**
