### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by iovis9**

### CODE REVIEW

**Comment by tpenguinltg** [comment]
> What's the benefit of all the various sizes?
Smaller downloads. You want your favicon to be as small as possible.

At minimum, we just need a favicon.ico or a single PNG and specify that in one `link`  tag.

**Comment by iovis9** [comment]
Just following best practices (lots of different platform expect lots of different kinds of favicon). If you want I can just throw the single icon and be done with it.

**Comment by iovis9** [comment]
http://realfavicongenerator.net/faq

**Comment by igrigorik** [comment]
Honestly, the number of files here seems like overkill.. Let's simplify it.

**Comment by iovis9** [comment]
Sure. Any suggestions?

**Comment by igrigorik** [comment]
To keep thing simple, target 1x case with 48x48 icon? I think that's probably sufficient for now.

**Comment by iovis9** [comment]
The 48x48 is just for Android. I'll just do the 16x16 and 32x32.
Can you explain why you feel this is overkill? This is honestly standard favicon support.

**Pull request merged**
