### PR TITLE
[Feature] Added new OmniAuth provider GitHub

### PR DESCRIPTION
**Pull request by despotes**
# OAuth Integration and Profile Updates

## Description:

This pull request aims to enhance the Vimgolf application by introducing:
- OmniAuth Github 
- OAuth Page
- Improvements to the user profile page functionality, to avoid collisions with user that have same nickname but different providers.

# Changes
- Added the `omniauth-github` gem to enable GitHub OAuth integration. (e46be342ab696393b271096a5b237efdbbe4141f)
- Updated the configuration files (`config/initializers/omniauth.rb` and `config/routes.rb`) to support dynamic provider routing and accommodate the GitHub provider. (e495dcc2adb08dc7dd31744fb60104776d99fc25)
- Created a new OAuth page with buttons for different providers (GitHub and Twitter). (2af42363d2618154934cf2f89f27af8b1fbf1b12)
- Improved the user profile page to display the appropriate provider link based on the user's sign-in method.  (c9d24199b40e923612b6f9d5bc8e87dab46f8c54)
- Modified the profile endpoint to `/:id/:username` to prevent collisions between users with the same nickname but different providers. (8f8b5e36171ffadf1cba1ffd11b6a9017bf545fb)
- Refactored and added tests to cover the new OAuth functionality and updated profile endpoints. (612da657aef1f44ab2667964a0a7c831964352ce)
- Updated the command-line interface (CLI) messages to align with the changes in the OAuth authentication flow. (091bbdec9eb2fe75d2fdb7b7353379bfdefb3c5d)

These updates enhance the user experience by providing OAuth login options and ensuring accurate profile information. The code has been thoroughly tested and is ready for review and integration into the main codebase.

Please review and merge this pull request. Thank you for your time and consideration!

### CODE REVIEW

**Comment by stablestud** [comment]
@filbranden I think this is something for you

**Comment by igrigorik** [comment]
Nice work, thank you!

**Comment by despotes** [comment]
> Nice work, thank you!

Thank you @igrigorik, one importantt thing is that who has the production access needs to add the environment variables for github oauth:
- `GITHUB_OAUTH_ID`
- `GITHUB_OAUTH_SECRET`

```
provider(
    :github,
    ENV.fetch('GITHUB_OAUTH_ID', 'dev'),
    ENV.fetch('GITHUB_OAUTH_SECRET', 'dev')
  )
```

**Comment by ic-768** [comment]
Following the [vimgolf site's](https://www.vimgolf.com/) instructions -  i.e. gem install and vimgolf setup - there is no mention of using github auth, only prompting only for a twitter key. 

If github auth is supported could we have some better instructions on how to use it?

**Comment by despotes** [comment]
> Following the [vimgolf site's](https://www.vimgolf.com/) instructions - i.e. gem install and vimgolf setup - there is no mention of using github auth, prompting only for a twitter key.
> 
> If github auth is supported could we have some better instructions on how to use it?

It seems that while the implementation for GitHub oAuth is in place, the repository owner might not have had the time to add the necessary client secret and client Id during the deployment phase. Only the repository owner @igrigorik , as far I know, can incorporate these keys securely. So, even if GitHub auth is supported in the codebase, it might not be functional until those keys are integrated.

sorry for the inconvenience

**Pull request merged**
