### PR TITLE
Display all challenge solutions per user

### PR DESCRIPTION
**Pull request by filbranden**
This implements #271. It borrows from some ideas from #272 (cc @Hettomei), mainly the URL route, controller and the SubmissionsPerUser class. But it uses a fairly rich and complex Mongo query, in order to get the ranking of the best entry and the "would-be" ranking of the other antries. It also adds links to the per-user page from different places.

### CODE REVIEW

**Comment by filbranden** [comment]
Ping @igrigorik and @Hettomei, would you take a look and see if you think something like this is workable?

Happy to make changes to the PR, but I'd like some initial feedback, before I spend more time here...

Thanks!

**Comment by Hettomei** [comment]
Hi,

Long time I used ruby / rails so I no more know what is relevant between mongo / ruby / rails version

But, using the "how to contribute / installation / with docker mongo" I tried to run the app on your branch.

Going to http://localhost:8080/challenges/---chanllengeid- I get an error : 

```
 Showing /home/tgauthier/programmes/vimgolf/app/views/challenges/show.erb where line #15 raised:

Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. (292)
```

Is it because of early work in progress or not expected ?

I used : 
`bundle exec rake db:drop db:setup challenges=500 users=10000 entries=2000` and stopped when I add : 
` 10000 active golfers, 422000 entries, 211 challenges `

**Comment by filbranden** [comment]
> Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. (292)

Oh sorry I fixed that in #297 which was merged already.

I just rebased this PR onto the master branch including that commit, so this shouldn't happen anymore.

Thanks for taking a first look already! Let me know if the rebase was enough to fix it for you.

Cheers,
Filipe

**Comment by Hettomei** [comment]
It works well.

Performance looks ok.

I see you prevented one user from seing all solution of another if he didn't play the challenge. Nice

**Review by Hettomei — APPROVED** [review]

**Comment by filbranden** [comment]
So, codeclimate is not very happy with the diff but mainly regarding length of some source files, classes and functions... But that's mainly about the definition of the Mongo queries.

I'm wondering if you think this is OK as is, or if it could use some refatoring to clean up some of these issues. Let me know, happy to put some more work into it, but I'd prefer to have some guidance of what you think is still necessary, if anything.

Cheers!
Filipe

**Comment by igrigorik** [comment]
Overall 👍 but yeah, let's fix the codeclimate issues. I'll defer to your judgement: follow the recommendations where it makes sense, and if it doesn't feel free to add an exception flag to get CC to stop complaining.

**Comment by filbranden** [comment]
Alright, I have addressed all the code climate issues!

I added test coverage for the `SubmissionsPerUser` service, which was the main complaint.

There were complaints from code climate itself and also Rubocop on `repository_challenge.rb`, regarding length of the file, of methods in the file and some code repetition. The issue I had with those are that `repository_challenge.rb` is essentially just encoding MongoDB queries in pseudo-db in Ruby, so that file is mostly encoding *data structures* and not really Ruby *code*. The code climate and Rubocop warnings are primarily meant to make *code* more readable and better, so I'm not sure how appropriate they were here... (Furthermore, pre-existing methods in that file already violated the method length rules.)

While I looked at moving things around to comply with the recommendations, I didn't really feel that this improved the code (which, again, is mostly comprised of encoded *data structures*) in that file.

So I ended up opting to exclude it from code climate warnings, by adding the `app/repositories/` to the exclude list in `.codeclimate.yml` in the top-level.

Do you agree with that decision? If so, please go ahead and merge!

If you have better suggestions to refactor that file, let me know (please make specific recommendations if possible), I'd be happy to work on it a little further.

Cheers!
Filipe

**Comment by filbranden** [comment]
Ping @igrigorik and @Hettomei on deploying this to the live website... Thanks!

**Comment by Hettomei** [comment]
@igrigorik I can do an heroku deploy if you want. let me know.

**Comment by igrigorik** [comment]
@Hettomei sounds good, give it a shot!

**Comment by Hettomei** [comment]
@filbranden it s online

And I can see http://www.vimgolf.com/challenges/55b18bbea9c2c30d04000001/user/zmf_tim (The big "Simple, Practical, and Common")

So everyone can be nostalgic and read again 'hidden' comments :) 

Thanks for the work.

@igrigorik for your information, there is a little commit " switch twitter avatar service; avatars.io is down" which is only on heroku's git and not here on github.

**Comment by filbranden** [comment]
Awesome! Thank you so much @Hettomei !

BTW, I tested the changes in #293 and I see they seem to work for users with very few (like 2) challenges:
http://www.vimgolf.com/albert07971271?ranking=1

But they seem to fail (rather quickly) for users with many challenges:

```
We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.
```

I'm guessing it's a Heroku limit on how long it can take to build the page... So I guess that one is not as easy to solve as I expected... Oh well.

**Comment by Hettomei** [comment]
I replied on #293 regarding "We're sorry, but something went wrong."

**Pull request merged**
