### PR TITLE
Make work in docker 

### PR DESCRIPTION
**Pull request by kramos**

### CODE REVIEW

**Comment by kramos** [comment]
This Dockerfile and shellscript lets you build a Docker image which means vimgolf can be ran as a container.  See https://registry.hub.docker.com/u/kramos/vimgolf/

**Comment by igrigorik** [comment]
Neat. 

Question: do these files actually need to live in this repo? It seems like container and instructions both reference your repo?

**Comment by kramos** [comment]
The instructions could be made to reference a DockerHub image linked to your account or I could make the DockerHub image build against your GitHub repo.

**Comment by timvisher** [comment]
lol. I love Docker but this seems a step too far. :P

When I saw the PR description I thought it was for running the server.

**Comment by igrigorik** [comment]
@kramos apologies about the super tardy reply.. I'll close this without merging. We haven't seen much demand for this, and I'd prefer to keep the core clean and up to date. If more folks start asking for a Docker wrapper, we can revisit. Thanks!

**Pull request closed without merging**
